version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/collector"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry-deps-collector:
        patterns:
          - "*opentelemetry*"
  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry-deps-java:
        patterns:
          - "io.opentelemetry.*"
  - package-ecosystem: "npm"
    directory: "/nodejs"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
  - package-ecosystem: "npm"
    directory: "/nodejs/packages/layer"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry-deps-nodejs:
        patterns:
          - "@opentelemetry/*"
    rebase-strategy: "auto"
  - package-ecosystem: "pip"
    directory: "/python/src/otel"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry-deps-python:
        patterns:
          - "opentelemetry-*"
  - package-ecosystem: "bundler"
    directory: "/ruby/src/layer"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry-deps-ruby:
        patterns:
          - "opentelemetry-*"
