extensions:
  solarwindsapmsettings:
    endpoint: "apm.collector.${SW_APM_DATA_CENTER}.cloud.solarwinds.com:443"
    key: "${SW_APM_API_TOKEN}:${OTEL_SERVICE_NAME}"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"

processors:
  decouple:
  resourcedetection:
    detectors: [env, system, lambda]
    timeout: 0.2s
    override: false
  resource:
    attributes:
      - key: sw.cloud.aws.resource.type
        value: "lambda"
        action: upsert

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: "https://otel.collector.${SW_APM_DATA_CENTER}.cloud.solarwinds.com:443"
    headers:
      Authorization: "Bearer ${SW_APM_API_TOKEN}"

service:
  extensions: [solarwindsapmsettings]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource,resourcedetection,decouple]
      exporters: [otlp,logging]
    metrics:
      receivers: [otlp]
      processors: [resource,resourcedetection,decouple]
      exporters: [otlp,logging]
  telemetry:
    metrics:
      address: localhost:8888
