name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: "40 3 * * *" # Run daily at 3:40 AM

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue was marked stale. It will be closed in 30 days without additional activity.'
          close-issue-message: 'Closed as inactive. Feel free to reopen if this issue is still relevant.'

          stale-pr-message: 'This PR was marked stale. It will be closed in 30 days without additional activity.'
          close-pr-message: 'Closed as inactive. Feel free to reopen if this PR is still being worked on.'

          days-before-stale: 365
          days-before-close: 30

          operations-per-run: 500
