name: "Release Combined Java Lambda Layer"

on:
  push:
    tags:
      - combined-layer-java/**

permissions:
  contents: read

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Create Release
        run: gh release create ${{ github.ref_name }} --draft --title ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-combined-layer:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: create-release
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
        layer_type:
          - javaagent
          - wrapper
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4.3.0
        with:
          distribution: temurin
          java-version: 17

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: collector/go.mod

      - name: Build Combined Layer
        run: |
          cd java
          ARCHITECTURE=${{ matrix.architecture }} LAYER_TYPE=${{ matrix.layer_type }} ./build-combined.sh
        env:
          ARCHITECTURE: ${{ matrix.architecture }}
          LAYER_TYPE: ${{ matrix.layer_type }}

      - name: Rename zip file for architecture and type
        run: |
          mv build/otel-java-${{ matrix.layer_type }}-extension-layer.zip build/otel-java-${{ matrix.layer_type }}-extension-layer-${{ matrix.architecture }}.zip
        working-directory: java

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        name: Save assembled combined layer to build
        with:
          name: otel-java-${{ matrix.layer_type }}-extension-layer-${{ matrix.architecture }}.zip
          path: java/build/otel-java-${{ matrix.layer_type }}-extension-layer-${{ matrix.architecture }}.zip
          
      - name: Add Binary to Release
        run: |
          gh release upload ${{github.ref_name}} java/build/otel-java-${{ matrix.layer_type }}-extension-layer-${{ matrix.architecture }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-combined-layer:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/layer-publish.yml
    needs: build-combined-layer
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
        layer_type:
          - javaagent
          - wrapper
        aws_region:
          - ap-northeast-1
          - ap-northeast-2
          - ap-south-1
          - ap-southeast-1
          - ap-southeast-2
          - ca-central-1
          - eu-central-1
          - eu-north-1
          - eu-west-1
          - eu-west-2
          - eu-west-3
          - sa-east-1
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
    with:
      artifact-name: otel-java-${{ matrix.layer_type }}-extension-layer-${{ matrix.architecture }}.zip
      layer-name: otel-java-${{ matrix.layer_type }}-extension
      component-version: "combined"
      architecture: ${{ matrix.architecture }}
      runtimes: java11 java17 java21
      release-group: prod
      aws_region: ${{ matrix.aws_region }}
    secrets: inherit